//LOAD USER 

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';


export const LOAD_CITY_REQUEST = 'LOAD_CITY_REQUEST';
export const LOAD_CITY_SUCCESS = 'LOAD_CITY_SUCCESS';
export const LOAD_CITY_FAILURE = 'LOAD_CITY_FAILURE';

export const LOAD_ZIP_REQUEST = 'LOAD_ZIP_REQUEST';
export const LOAD_ZIP_SUCCESS = 'LOAD_ZIP_SUCCESS';
export const LOAD_ZIP_FAILURE = 'LOAD_ZIP_FAILURE';